// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTV0UD-ijjA9qe9QAAdVEifPoitom55DU',
    appId: '1:765310118545:web:31d0dfba2376f2c208ed30',
    messagingSenderId: '765310118545',
    projectId: 'timemanager-e01f3',
    authDomain: 'timemanager-e01f3.firebaseapp.com',
    storageBucket: 'timemanager-e01f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-FwMJBntKdUEPrGCpzwk14XVDbkn2_xk',
    appId: '1:765310118545:android:7d6c35d91811b0da08ed30',
    messagingSenderId: '765310118545',
    projectId: 'timemanager-e01f3',
    storageBucket: 'timemanager-e01f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWH7qyJq1Lin5x6KqsZCMuOS-F9jJaTVo',
    appId: '1:765310118545:ios:42aa1cde84f7df8f08ed30',
    messagingSenderId: '765310118545',
    projectId: 'timemanager-e01f3',
    storageBucket: 'timemanager-e01f3.firebasestorage.app',
    iosBundleId: 'com.example.timemanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWH7qyJq1Lin5x6KqsZCMuOS-F9jJaTVo',
    appId: '1:765310118545:ios:42aa1cde84f7df8f08ed30',
    messagingSenderId: '765310118545',
    projectId: 'timemanager-e01f3',
    storageBucket: 'timemanager-e01f3.firebasestorage.app',
    iosBundleId: 'com.example.timemanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTV0UD-ijjA9qe9QAAdVEifPoitom55DU',
    appId: '1:765310118545:web:17fca8055fbb6fb308ed30',
    messagingSenderId: '765310118545',
    projectId: 'timemanager-e01f3',
    authDomain: 'timemanager-e01f3.firebaseapp.com',
    storageBucket: 'timemanager-e01f3.firebasestorage.app',
  );
}
