// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNLc0HegGS4jAK9iAoFbyaP8NCcmM6or0',
    appId: '1:607753279046:web:8843439e0eb7bd639e5c47',
    messagingSenderId: '607753279046',
    projectId: 'spendmanager-341f8',
    authDomain: 'spendmanager-341f8.firebaseapp.com',
    storageBucket: 'spendmanager-341f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9y0cmBf9K5zxYUho5F_eqbUoO5-fdWrc',
    appId: '1:607753279046:android:15c8f692434ff2c49e5c47',
    messagingSenderId: '607753279046',
    projectId: 'spendmanager-341f8',
    storageBucket: 'spendmanager-341f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABj6lPC_vla3Gl9eXFRIYAYY43pjkd-yU',
    appId: '1:607753279046:ios:5f531d69d8f17b4c9e5c47',
    messagingSenderId: '607753279046',
    projectId: 'spendmanager-341f8',
    storageBucket: 'spendmanager-341f8.firebasestorage.app',
    iosBundleId: 'com.spendmanager.spendmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABj6lPC_vla3Gl9eXFRIYAYY43pjkd-yU',
    appId: '1:607753279046:ios:5f531d69d8f17b4c9e5c47',
    messagingSenderId: '607753279046',
    projectId: 'spendmanager-341f8',
    storageBucket: 'spendmanager-341f8.firebasestorage.app',
    iosBundleId: 'com.spendmanager.spendmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNLc0HegGS4jAK9iAoFbyaP8NCcmM6or0',
    appId: '1:607753279046:web:7555b751dc64ce299e5c47',
    messagingSenderId: '607753279046',
    projectId: 'spendmanager-341f8',
    authDomain: 'spendmanager-341f8.firebaseapp.com',
    storageBucket: 'spendmanager-341f8.firebasestorage.app',
  );
}
